package pe.edu.pucp.onepucp.postulaciones.model;

public enum EstadoPostulacion {
    ESPERA_PASAR_PRIMER_FILTRO,
    PASO_PRIMER_FILTRO,
    NO_PASO_PRIMER_FILTRO,
    ESPERA_PASAR_SEGUNDO_FILTRO,
    PASO_SEGUNDO_FILTRO,
    NO_PASO_SEGUNDO_FILTRO,
    PASO_FILTRO_FINAL,
    NO_PASO_FILTRO_FINAL
}
