package pe.edu.pucp.onepucp.solicitudes.model;

public enum EstadoPostulacion {
    INACTIVA,
    ESPERA_PASAR_PRIMERA_APROBACION,
            PASO_PRIMERA_APROBACION,
    NO_PASO_PRIMERA_APROBACION,
            ESPERA_PASAR_SEGUNDA_APROBACION,
    PASO_SEGUNDA_APROBACION,
            NO_PASO_SEGUNDA_APROBACION,
    ESPERA_PASAR_TERCERA_APROBACION,
            PASO_TERCERA_APROBACION,
    NO_PASO_TERCERA_APROBACION
}
