package pe.edu.pucp.onepucp.solicitudes.model;

public enum TipoSolicitud {
    SOLICITUD_JURADOS,SOLICITUD_MATRICULA,SOLICITUD_TEMA_TESIS,
    PERSONAL_ADMINISTRATIVO,ADMINISTRADOR,CARTA_PRESENTACION,INFORMACION_ALUMNOS_EN_RIESGO,
    SOLICITUD_PEDIDOS_CURSO
}
